apiVersion: apps/v1
kind: Deployment
metadata:
  name: zy-es-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zy-es-operator
  template:
    metadata:
      labels:
        name: zy-es-operator
    spec:
      serviceAccountName: zy-es-operator
      containers:
        - name: zy-es-operator
          # Replace this with the built image name
          image: zyseeker/es-operator:v1
          command:
          - zy-es-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zy-es-operator"
